---
steps:
  - type: "waiter"

  - name: ":docker:"
    command: ".buildkite/bin/build"
    agents:
      docker: builder
      queue: native

  - type: "waiter"

  - name: ":pill: Spec Tests"
    command: ".buildkite/bin/test-spec"
    agents:
      queue: native

  - name: ":pill: Unit Tests"
    command: ".buildkite/bin/test-units"
    agents:
      queue: elastic

  - name: ":rocket: Publish"
    type: "manual"
    branches: master

  - type: "waiter"

  - name: ":package: Deploy"
    command: "./.buildkite/bin/deploy"
    agents:
      queue: elastic
    branches: master

  - type: "waiter"

  - name: ":loudspeaker:"
    command: "./.buildkite/bin/announce"
    agents:
      queue: elastic
    branches: master
